### ISSUE TITLE
Server not loading

### ISSUE THREAD

**Issue by SebCanet** [arrowhead-tools/mgmt-tool-js#11]
Hi,
I put my new pb on this issue, after installing I obtain this log:

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:67:19)
at Object.createHash (node:crypto:130:10)
at module.exports (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\util\createHash.js:135:53)
at NormalModule._initBuildHash (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:417:16)
at handleParseError (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:471:10)
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:503:5
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:358:12
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
at iterateNormalLoaders (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
at iterateNormalLoaders (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\react-scripts\scripts\start.js:19
throw err;
^

Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:67:19)
at Object.createHash (node:crypto:130:10)
at module.exports (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\util\createHash.js:135:53)
at NormalModule._initBuildHash (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:417:16)
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:452:10
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:323:13
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:367:11
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:233:18
at context.callback (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\babel-loader\lib\index.js:59:103 {
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
ERROR: "start-js" exited with 1.

I think solution is here: [https://roytuts.com/how-to-fix-err_ossl_evp_unsupported-in-react-js-application/](https://roytuts.com/how-to-fix-err_ossl_evp_unsupported-in-react-js-application/)

**Comment by tsvetlin** [comment]
Hey! 

Could you please try it out, and if works submit a PR?

Thank you,
Svetlin

**Comment by SebCanet** [comment]
I'm working on it, still not functionnal, but I'm on W10x64, node 17.1.0. Maybe it's different on Linux ? Did you try on a VM with node 17 ?

**Comment by SebCanet** [comment]
It works, but with old libraries, so I have a lot of security warnings:
$ npm install
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated html-webpack-plugin@4.0.0-beta.11: please switch to a stable version
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated material-ui-pickers@2.2.4: You can now upgrade to @material-ui/pickers. Documentation for v2 can be found at https://material-ui-pickers-v2.dmtr-kovalenko.now.sh/
npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

**Comment by Iinksafe** [comment]
Hello there @SebCanet! The request module is deprecated. Please see https://github.com/request/request/issues/3142 for more information.

**Comment by SebCanet** [comment]
And what should we do to resolve all this security warnings?

**Comment by tsvetlin** [comment]
If you wish, you can update them. Just make sure nothing breaks in the process. They tend to, hence I did not touch them.
