### ISSUE TITLE
Management-tool crashes after pressing Escape button

### ISSUE THREAD

**Issue by Msegun** [arrowhead-tools/mgmt-tool-js#4]
Steps to reproduce:

1. Run management-tool in docker.
2. On the registry page press "Add" Button.
3. Once the popup opens click on the "System Name" input field
4. Press Escape.

Expected result
  The popup should close.
Result  
  The app crashes.

![image](https://user-images.githubusercontent.com/16302579/92487263-51caa680-f1ed-11ea-92cc-15849c48be90.png)

**Comment by tsvetlin** [comment]
Thank you for reporting the issue, I'll fix it.

**Comment by tsvetlin** [comment]
Fixed with 4.4.0 release of the Management Tool
