### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by SebCanet** [arrowhead-tools/mgmt-tool-js#6]
Hi,
with Node v16 and no updating package.json, the npm install command blocks:

$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @material-ui/core@4.11.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"3.8.1" from the root project
npm ERR!   peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.2
npm ERR!   node_modules/@material-ui/icons
npm ERR!     @material-ui/icons@"^3.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @material-ui/core@"3.8.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.3.0" from @material-ui/core@3.8.1
npm ERR!   node_modules/@material-ui/core
npm ERR!     @material-ui/core@"3.8.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\babas\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\babas\AppData\Local\npm-cache\_logs\2021-04-28T15_08_04_237Z-debug.log

Many thanks for your help.

**Comment by tsvetlin** [comment]
Hey! Thanks for the report! I'll look into it!

**Comment by SebCanet** [comment]
I tested with node v15, or v14, it's same pb. 
If I try to update all packages in package.json declaration, it's still same circular dependancies problem.
I tried with beta and alpha new packages for material-ui v5, and dependencies, but still same kind of problem.
Hope this could help.

**Comment by tsvetlin** [comment]
Fixed with 4.4.0 release of the Management Tool

**Comment by SebCanet** [comment]
Thanks, but install works only with Python v2.7, not v3.
There are also dependencies problems with their latest versions.
By the way, on Windows 10 I have errors on 'nom start':
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:503:5
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:358:12
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:417:16)
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:452:10
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:323:13
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
ERROR: "start-js" exited with 1.

**Comment by tsvetlin** [comment]
Hello!

Try deleting the node_modules folder and package-lock.json file, then please run npm install again.

How is python version relevant in a node project?

**Comment by SebCanet** [comment]
Hi, thanks for your quick answer!
Still have the same problem, but sometimes on Windows it's a path problem. I already used cross-env for your nodejs example, but this time it does not resolve problem (same as above).

About Python, I don't know but I think the gyp install compiles something. I have only v3 and during install I had messages with module looking for v2.7, after installing it, it worked. Here it is (sorry):
$ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\svgo\package.json'
npm WARN old lockfile  Could not fetch metadata for svgo@file:B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\svgo [Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\svgo\package.json'] {
npm WARN old lockfile   errno: -4058,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: 'B:\\Projets\\nodejs_tests\\mgmt-tool-js-master\\node_modules\\svgo/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\tsconfig-paths\package.json'
npm WARN old lockfile  Could not fetch metadata for tsconfig-paths@file:B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\tsconfig-paths [Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\tsconfig-paths\package.json'] {
npm WARN old lockfile   errno: -4058,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: 'B:\\Projets\\nodejs_tests\\mgmt-tool-js-master\\node_modules\\tsconfig-paths/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\url-loader\package.json'
npm WARN old lockfile  Could not fetch metadata for url-loader@file:B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\url-loader [Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\url-loader\package.json'] {
npm WARN old lockfile   errno: -4058,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: 'B:\\Projets\\nodejs_tests\\mgmt-tool-js-master\\node_modules\\url-loader/package.json'
npm WARN old lockfile }
npm WARN old lockfile Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\watchpack-chokidar2\package.json'
npm WARN old lockfile  Could not fetch metadata for watchpack-chokidar2@file:B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\watchpack-chokidar2 [Error: ENOENT: no such file or directory, open 'B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\watchpack-chokidar2\package.json'] {
npm WARN old lockfile   errno: -4058,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: 'B:\\Projets\\nodejs_tests\\mgmt-tool-js-master\\node_modules\\watchpack-chokidar2/package.json'
npm WARN old lockfile }
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated html-webpack-plugin@4.0.0-beta.11: please switch to a stable version
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated material-ui-pickers@2.2.4: You can now upgrade to @material-ui/pickers. Documentation for v2 can be found at https://material-ui-pickers-v2.dmtr-kovalenko.now.sh/
npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'B:\\Projets\\nodejs_tests\\mgmt-tool-js-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.1.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
npm ERR! gyp verb `which` failed Error: not found: C:\Python27\python.exe
npm ERR! gyp verb `which` failed     at getNotFoundError (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  C:\Python27\python.exe Error: not found: C:\Python27\python.exe
npm ERR! gyp verb `which` failed     at getNotFoundError (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "C:\Python27\python.exe". checking python launcher
npm ERR! gyp verb could not find "C:\Python27\python.exe". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "C:\Python27\python.exe", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "B:\\Projets\\nodejs_tests\\mgmt-tool-js-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\node-sass
npm ERR! gyp ERR! node -v v17.1.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by tsvetlin** [comment]
I don't have a windows machine, so I can't test nor fix it. Looking at the error logs it seems to me it wants to use Python 2.7 indeed, but you only have 3. Could you please try installing 2.7 too, just to check?

**Comment by SebCanet** [comment]
That's what I did, it installs everything but I obtain this log:

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:67:19)
at Object.createHash (node:crypto:130:10)
at module.exports (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\util\createHash.js:135:53)
at NormalModule._initBuildHash (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:417:16)
at handleParseError (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:471:10)
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:503:5
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:358:12
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
at iterateNormalLoaders (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
at iterateNormalLoaders (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\react-scripts\scripts\start.js:19
throw err;
^

Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:67:19)
at Object.createHash (node:crypto:130:10)
at module.exports (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\util\createHash.js:135:53)
at NormalModule._initBuildHash (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:417:16)
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:452:10
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\webpack\lib\NormalModule.js:323:13
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:367:11
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:233:18
at context.callback (B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
at B:\Projets\nodejs_tests\mgmt-tool-js-master\node_modules\babel-loader\lib\index.js:59:103 {
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
ERROR: "start-js" exited with 1.
